// src/App.jsx
import { useEffect, useMemo, useRef, useState } from "react";
import "antd/dist/antd.css";
import { Menu } from "antd";
import { PlusOutlined, MenuOutlined, GithubOutlined } from "@ant-design/icons";
import "./App.css";

function App() {
  // 定数

  const KEY_NOTES = "notes";
  const MAX_NOTE_COUNT = 100;

  // リアクティブ変数

  const [isListShow, setListShow] = useState(false);
  const [notes, setNotes] = useState(
    (JSON.parse(localStorage.getItem(KEY_NOTES)) || []).map(({ id, text }) => ({
      id,
      text,
      noteName: text.trim() ? text : "Empty",
    }))
  );
  const [selected, setSelected] = useState([]);
  const textarea = useRef(null);

  // 算出プロパティ

  const text = useMemo(() => {
    const id = selected[0];
    if (!id) {
      return "";
    }
    const note = notes.find((x) => x.id === id);
    return note.text;
  }, [notes, selected]);
  const handleChange = (event) => {
    const id = selected[0];
    const index = notes.findIndex((x) => x.id === id);
    const newNote = {
      id,
      text: event.target.value,
      noteName: event.target.value.trim() ? event.target.value : "Empty",
    };
    const newNotes = [
      newNote,
      ...notes.slice(0, index),
      ...notes.slice(index + 1),
    ];
    setNotes(newNotes);
    localStorage.setItem(
      KEY_NOTES,
      JSON.stringify(
        newNotes.map(({ id, text }) => ({
          id,
          text,
        }))
      )
    );
  };

  // ウォッチャー

  useEffect(() => textarea.current.focus(), [isListShow, selected]);

  // メソッド ハンドラー

  const addNote = () => {
    if(notes.length >0){
      if (notes[0].noteName === "Empty"){
        textarea.current.focus();
        return;
      }
    }
    const id = Math.random().toString(36).slice(2);
    const newNote = { id, text: "", noteName: "Empty" };
    setNotes([newNote, ...notes].slice(0, MAX_NOTE_COUNT));
    setSelected([id]);
  };

  const toggleList = () => setListShow(!isListShow);

  // ライフサイクル フック

  useEffect(() => addNote(), []);

  return (
    <div className="d-flex h-100">
      {/* ナビゲーション メニュー */}
      <Menu
        className="d-flex flex-column h-100"
        inlineCollapsed={true}
        items={[
          {
            key: "list",
            icon: <MenuOutlined />,
            title: 'Menu',
          },
          {
            key: "new",
            icon: <PlusOutlined />,
            title: 'New',
          },
          {
            icon: <GithubOutlined />,
            title: 'Github',
          },
        ]}
        mode="inline"
        onClick={({ key }) => {
          switch (key) {
            case "list":
              toggleList();
              break;
            case "new":
              addNote();
              break;
          }
        }}
        selectable={false}
        style={{
          minWidth: 56,
          width: 56,
        }}
      />

      {/* メモ リスト */}
      {isListShow && (
        <div className="list" style={{ minWidth: 300, overflow: "auto" }}>
          <Menu
            className="d-flex flex-column"
            items={notes.map((note) => ({
              label: note.noteName,
              key: note.id,
            }))}
            mode="inline"
            onSelect={({ key }) => setSelected([key])}
            selectedKeys={selected}
          />
        </div>
      )}

      {/* テキスト エリア */}
      <textarea
        className="px-2 text w-100"
        onChange={handleChange}
        ref={textarea}
        style={{ border: "initial" }}
        value={text}
      />
    </div>
  );
}

export default App;

// src/App.vue
<script setup>
import { ref, computed, watch, nextTick } from "vue";

// 定数

const KEY_NOTES = "notes";
const MAX_NOTE_COUNT = 100;

// リアクティブ変数

const isListShow = ref(false);
const notes = ref(JSON.parse(localStorage.getItem(KEY_NOTES)) || []);
const selected = ref([]);
const textarea = ref(null);

// 算出プロパティ

const text = computed({
  get() {
    const id = selected.value[0];
    const note = notes.value.find((x) => x.id === id);
    if(note.text == ""){
      note.text = "Empty"
    }
    return note.text;
  },
  set(newValue) {
    const id = selected.value[0];
    const index = notes.value.findIndex((x) => x.id === id);
    const newNote = { id, text: newValue };
    notes.value = [
      newNote,
      ...notes.value.slice(0, index),
      ...notes.value.slice(index + 1),
    ];
    localStorage.setItem(KEY_NOTES, JSON.stringify(notes.value));
  },
});

// ウォッチャー

watch([isListShow, selected], async () => {
  await nextTick();
  textarea.value.focus();
});

// メソッド ハンドラー

const addNote = () => {
  const id = Math.random().toString(36).slice(2);
  const newNote = { id, text: "" };
  notes.value = [newNote, ...notes.value].slice(0, MAX_NOTE_COUNT);
  selected.value = [id];
};

const toggleList = () => (isListShow.value = !isListShow.value);

// ライフサイクル フック

addNote();
</script>

<template>
  <v-app>
    <v-main>
      <div class="d-flex h-100">
        <!-- ナビゲーション メニュー -->
        <div class="d-flex h-100">
          <v-list class="d-flex flex-column h-100">
            <v-list-item @click="toggleList">
              <v-list-item-icon icon="mdi-note-multiple-outline" />
            </v-list-item>
            <v-list-item @click="addNote">
              <v-list-item-icon icon="mdi-creation" />
            </v-list-item>
            <v-list-item
              class="mt-auto"
              href="https://github.com/AsaiToshiya/n" target="_blank"
            >
              <v-list-item-icon icon="mdi-github" />
            </v-list-item>
          </v-list>
          <v-divider class="mx-0" vertical />
        </div>

        <!-- メモ リスト -->
        <div v-if="isListShow" class="d-flex h-100">
          <v-list
            v-model:selected="selected"
            :items="notes"
            class="d-flex flex-column list"
            density="compact"
            item-title="text"
            item-value="id"
            :mandatory="true"
          />
          <v-divider class="mx-0" vertical />
        </div>

        <!-- テキスト エリア -->
        <textarea ref="textarea" v-model="text" class="px-2 text w-100" />
      </div>
    </v-main>
  </v-app>
</template>

<style>
.list {
  max-width: 300px;
  width: 300px;
}

.text {
  resize: none;
}

.text:focus {
  outline: none;
}
</style>
